name: minit
version: '1.0'
grade: stable
title: minit
summary: peculiar little adventure played sixty seconds at a time 
description: Minit is a peculiar little adventure played sixty seconds at a time. Journey outside the comfort of your home to help unusual folk, uncover countless secrets, and overcome dangerous foes, all in hopes of lifting a rather unfortunate curse that ends each day after just one minute. 

confinement: strict
base: core18

architectures:
  - build-on: ['i386', 'amd64']
    run-on: ['i386', 'amd64']


apps:
  minit:
    # Set the driver path: https://docs.mesa3d.org/envvars.html
    command: minit/minit
    environment:
      LIBGL_DRIVERS_PATH: /snap/minit/current/usr/lib/i386-linux-gnu/dri/
    #extensions: [gnome-3-28]
    plugs:
      - opengl
      - audio-playback

parts:
  enable-i386:
    # Borrowed from https://forum.snapcraft.io/t/32bit-stage-packages-in-64bit-build/3134
    plugin: nil
    override-pull: |
      dpkg --add-architecture i386
      apt-get update

  minit:
    plugin: nil
    after: [enable-i386]
    source: .
    override-pull: |
      dpkg --add-architecture i386
      apt-get update
      snapcraftctl pull
    override-build: |
      apt install -y libopenal1:i386 libc6:i386
      dpkg -i minit.deb
      cp -r /opt/minit ../install/
      echo "fullscreen=1" >> ../install/minit/assets/options.ini
    # No build packages -- the apt install line here *should*i(?) work, but
    # empirically doesn't (nor did the instructions in
    # https://forum.snapcraft.io/t/32bit-stage-packages-in-64bit-build/3134,
    # probably because "prepare" has different semantics than override-*)
    stage:
        - minit/

  runtime-deps:
    plugin: nil
    after: [enable-i386]
    stage-packages:
      # Required by the .deb
      - libopenal1:i386
      - libc6:i386
      # Other needed packages
      - libstdc++6:i386
      - libglu1-mesa:i386
      - libssl1.0.0:i386
      - libxext6:i386
      - libxrandr2:i386
      - libxxf86vm1:i386
      # Video "drivers" -- gnome extension would have these, but only amd64...
      - va-driver-all:i386
