name: minit
version: '1.0'
grade: stable
title: minit
summary: peculiar little adventure played sixty seconds at a time 
description: Minit is a peculiar little adventure played sixty seconds at a time. Journey outside the comfort of your home to help unusual folk, uncover countless secrets, and overcome dangerous foes, all in hopes of lifting a rather unfortunate curse that ends each day after just one minute. 

confinement: strict
base: core18

apps:
  minit:
    command: runner
    plugs:
      - kde-frameworks-5-plug
      - home
      - opengl
      - network
      - network-bind
      - audio-playback

parts:
  minit:
    plugin: nil
    source: .
    override-build: cp -r assets/ runner ../install/
    stage:
        - assets/
        - runner

  runtime-deps:
    plugin: nil
    stage-packages:
      - libopenal1
      - libc6
